import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:foodmarket_flutter_fe/shared/shared.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:supercharged/supercharged.dart';
import 'package:get/get.dart';
part 'general_page.dart';
part 'sign_in_page.dart';
part 'sign_up_page.dart';